In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [2]:
print("Hello")

Hello

In [15]:
data = pd.read_csv("C:/Users/srini/Desktop/IV/UPI/banks.csv")

In [16]:
data

,Month,No. of Banks live on UPI,Volume (in Mn),Value,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8
0,Jan-23,399,"8,685.30","1,410",NaN,NaN,NaN,NaN,NaN
1,Feb-23,390,"7,534.76","1,236",NaN,NaN,NaN,NaN,NaN
2,Jan-23,385,"8,036.89","1,299",NaN,NaN,NaN,NaN,NaN
3,Dec-22,382,"7,829.49","1,282",NaN,NaN,NaN,NaN,NaN
4,Nov-22,376,"7,309.45","1,190.59","11,90,593",NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...
79,Aug-16,21,0.09,0.00,3,NaN,NaN,NaN,NaN
80,Jul-16,21,0.09,0.00,0,NaN,NaN,NaN,NaN
81,Jun-16,21,0,-,-,NaN,NaN,NaN,NaN
82,May-16,21,0,-,-,NaN,NaN,NaN,NaN
83,Apr-16,21,0,-,-,NaN,NaN,NaN,NaN

In [19]:
#normal viz

import pandas as pd
import matplotlib.pyplot as plt
df = pd.read_csv("C:/Users/srini/Desktop/IV/UPI/banks.csv")
months = df['Month']
transaction_values = df['Value']

plt.figure(figsize=(10, 6))
plt.style.use('dark_background')
colors = ['yellow']
plt.plot(months, transaction_values, color=colors[0])

plt.ylabel('Month')
plt.xlabel('Transaction Value')
plt.title('Monthly Transaction Value')
plt.grid(True, linestyle='--', alpha=0.5) 
plt.legend(['Transaction Value'], loc='upper left')
plt.show()

KeyError: 'Value'

In [12]:
import pandas as pd
import matplotlib.pyplot as plt
from matplotlib.animation import FuncAnimation

df = pd.read_csv("C:/Users/srini/Desktop/IV/UPI/banks.csv")

months = df['Month']
transaction_values = df['Value']

fig, ax = plt.subplots(figsize=(10, 6))
ax.set_title('Monthly Transaction Value Animation')
ax.set_xlabel('Month')
ax.set_ylabel('Value')
ax.set_xlim(months.iloc[0], months.iloc[-1])
ax.grid(True, linestyle='--', alpha=0.5)
line, = ax.plot([], [], color='yellow', label='Transaction Value')
ax.legend(loc='upper left')


def update(frame):
    
    x = months.iloc[:frame+1]
    y = transaction_values.iloc[:frame+1]
    line.set_data(x, y)
    return line,

ani = FuncAnimation(fig, update, frames=len(months), interval=500, blit=True)

plt.show()

KeyError: 'Value'